# Generated by Django 4.1 on 2022-09-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=200)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'db_blogs',
            },
        ),
    ]
